server:
  port: 8400

logging:
  level:
    root: info

spring:
  application:
    name: single-product
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.42:3306/demo_product?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

seata:
  application-id: ${spring.application.name}
  enabled: true
  tx-service-group: single-product-group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  use-jdk-proxy: true
  service:
    vgroup-mapping:
      single-product-group: default
    grouplist:
      default: 192.168.0.199:8091

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true